### ISSUE TITLE
Makefile是不是有问题

### ISSUE THREAD

**Issue by tzngit** [cloudwu/lua-serialize#4]
Makefile死活make不过，感觉是不是不对啊  我改成下边那样就make成功了
gcc -Wall -g -o serialize.so -fPIC --shared serialize.c -I/usr/local/lua/include
不知道对不对

**Comment by cloudwu** [comment]
makefile 随便写的， 根据你的平台和环境改改就可以了。

**Comment by tzngit** [comment]
好的，我已经成功改好make通过了 :grinning:
